### ISSUE TITLE
aditional events in the calender

### ISSUE THREAD

**Issue by ElevenSpins** [DU4L/CTFNote#8]
function to create aditional team events in the ctfnote calender.

**Comment by frereit** [comment]
I'd propose integrating this like this:
We add a new option 'Non-CTF Event' (better names are welcome)
![image](https://user-images.githubusercontent.com/18506129/150207314-986fefb0-9fdd-4a3f-8dbf-466c9ed8d4b5.png)

these events then get added to the calendar, but don't show up in the "Incoming" tab.
These events then live at /#/event/1-Team-Meeting/ and look almost like normal CTFs but there's "Notes" instead of "Tasks" and no credentials

**Comment by frereit** [comment]
I'd propose integrating this like this:
We add a new option 'Non-CTF Event' (better names are welcome)
![image](https://user-images.githubusercontent.com/18506129/150207314-986fefb0-9fdd-4a3f-8dbf-466c9ed8d4b5.png)

these events then get added to the calendar, but don't show up in the "Incoming" tab. There should be a way to check 'recurring' with typical options such as 'every month', 'every [weekday]', 'every first sunday of the month' or whatever.

They then live at `/#/event/1-Team-Meeting/` and look almost like normal CTFs but there's "Notes" instead of "Tasks" and no credentials.

![image](https://user-images.githubusercontent.com/18506129/150207680-b70602de-f97d-4d9a-ad89-6316d8031319.png)

For non-recurring events, the 'Notes' tab should just be a single hedgedoc iframe.

For recurring events (like the team meeting), there should be a hedgedoc iframe for each date, these could be created when they're accessed for the first time.

opinions on this approach? yes, no, better ideas?

**Comment by JM-Lemmi** [comment]
As discussed in #9, this will be replaced by an external outlook calendar. This issue will only need to display those additional entries, but not manage them.
